// Auto-generated by: supabase gen types typescript --local > types/database.ts
// Run `npm run db:types` to regenerate after schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      admin_audit_log: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          id: string
          payload: Json | null
          target_id: string | null
          target_type: string | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          id?: string
          payload?: Json | null
          target_id?: string | null
          target_type?: string | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          id?: string
          payload?: Json | null
          target_id?: string | null
          target_type?: string | null
        }
      }
      broker_promotions: {
        Row: {
          broker_id: string
          created_at: string
          custom_pitch: string | null
          ends_at: string
          id: string
          is_active: boolean
          product_id: string
          promotion_slot: number
          starts_at: string
        }
        Insert: {
          broker_id: string
          created_at?: string
          custom_pitch?: string | null
          ends_at: string
          id?: string
          is_active?: boolean
          product_id: string
          promotion_slot: number
          starts_at: string
        }
        Update: {
          broker_id?: string
          created_at?: string
          custom_pitch?: string | null
          ends_at?: string
          id?: string
          is_active?: boolean
          product_id?: string
          promotion_slot?: number
          starts_at?: string
        }
      }
      broker_supplier_assignments: {
        Row: {
          assigned_at: string
          broker_id: string
          supplier_id: string
        }
        Insert: {
          assigned_at?: string
          broker_id: string
          supplier_id: string
        }
        Update: {
          assigned_at?: string
          broker_id?: string
          supplier_id?: string
        }
      }
      brokers: {
        Row: {
          broker_share_pct: number
          commission_pct: number
          created_at: string
          fixed_fee_cents: number
          id: string
          legal_name: string
          status: string
          stripe_account_id: string | null
          stripe_onboarding_complete: boolean
          tax_id: string
          tax_jurisdiction: string
          updated_at: string
          user_id: string
          vat_number: string | null
        }
        Insert: {
          broker_share_pct?: number
          commission_pct?: number
          created_at?: string
          fixed_fee_cents?: number
          id?: string
          legal_name: string
          status?: string
          stripe_account_id?: string | null
          stripe_onboarding_complete?: boolean
          tax_id: string
          tax_jurisdiction?: string
          updated_at?: string
          user_id: string
          vat_number?: string | null
        }
        Update: {
          broker_share_pct?: number
          commission_pct?: number
          created_at?: string
          fixed_fee_cents?: number
          id?: string
          legal_name?: string
          status?: string
          stripe_account_id?: string | null
          stripe_onboarding_complete?: boolean
          tax_id?: string
          tax_jurisdiction?: string
          updated_at?: string
          user_id?: string
          vat_number?: string | null
        }
      }
      categories: {
        Row: {
          depth: number
          id: string
          marketplace_context: Database['public']['Enums']['marketplace_context']
          name: string
          parent_id: string | null
          slug: string
          sort_order: number
        }
        Insert: {
          depth?: number
          id?: string
          marketplace_context?: Database['public']['Enums']['marketplace_context']
          name: string
          parent_id?: string | null
          slug: string
          sort_order?: number
        }
        Update: {
          depth?: number
          id?: string
          marketplace_context?: Database['public']['Enums']['marketplace_context']
          name?: string
          parent_id?: string | null
          slug?: string
          sort_order?: number
        }
      }
      cities: {
        Row: {
          country_id: string
          id: string
          name: string
          retail_active: boolean
          slug: string
        }
        Insert: {
          country_id: string
          id?: string
          name: string
          retail_active?: boolean
          slug: string
        }
        Update: {
          country_id?: string
          id?: string
          name?: string
          retail_active?: boolean
          slug?: string
        }
      }
      countries: {
        Row: {
          created_at: string
          currency_code: string | null
          id: string
          is_active: boolean
          is_eu: boolean
          iso_code: string
          name: string
          vat_rate: number | null
        }
        Insert: {
          created_at?: string
          currency_code?: string | null
          id?: string
          is_active?: boolean
          is_eu?: boolean
          iso_code: string
          name: string
          vat_rate?: number | null
        }
        Update: {
          created_at?: string
          currency_code?: string | null
          id?: string
          is_active?: boolean
          is_eu?: boolean
          iso_code?: string
          name?: string
          vat_rate?: number | null
        }
      }
      invoices: {
        Row: {
          broker_id: string | null
          buyer_country: string | null
          buyer_vat_number: string | null
          conditions_passed: boolean | null
          conditions_payload: Json | null
          created_at: string
          id: string
          invoice_number: string
          issued_at: string | null
          order_id: string
          pdf_url: string | null
          status: Database['public']['Enums']['invoice_status']
          vat_treatment: string
        }
        Insert: {
          broker_id?: string | null
          buyer_country?: string | null
          buyer_vat_number?: string | null
          conditions_passed?: boolean | null
          conditions_payload?: Json | null
          created_at?: string
          id?: string
          invoice_number: string
          issued_at?: string | null
          order_id: string
          pdf_url?: string | null
          status?: Database['public']['Enums']['invoice_status']
          vat_treatment: string
        }
        Update: {
          broker_id?: string | null
          buyer_country?: string | null
          buyer_vat_number?: string | null
          conditions_passed?: boolean | null
          conditions_payload?: Json | null
          created_at?: string
          id?: string
          invoice_number?: string
          issued_at?: string | null
          order_id?: string
          pdf_url?: string | null
          status?: Database['public']['Enums']['invoice_status']
          vat_treatment?: string
        }
      }
      order_items: {
        Row: {
          id: string
          line_total_cents: number
          order_id: string
          product_id: string
          quantity: number
          unit_price_cents: number
          vat_rate: number
        }
        Insert: {
          id?: string
          line_total_cents: number
          order_id: string
          product_id: string
          quantity: number
          unit_price_cents: number
          vat_rate?: number
        }
        Update: {
          id?: string
          line_total_cents?: number
          order_id?: string
          product_id?: string
          quantity?: number
          unit_price_cents?: number
          vat_rate?: number
        }
      }
      orders: {
        Row: {
          broker_id: string | null
          buyer_country_id: string | null
          buyer_id: string
          created_at: string
          currency_code: string
          id: string
          idempotency_key: string | null
          marketplace_context: Database['public']['Enums']['marketplace_context']
          shipping_address: Json | null
          shipping_cents: number
          status: Database['public']['Enums']['order_status']
          stripe_checkout_session_id: string | null
          stripe_payment_intent_id: string | null
          subtotal_cents: number
          supplier_id: string
          total_cents: number
          updated_at: string
          vat_cents: number
        }
        Insert: {
          broker_id?: string | null
          buyer_country_id?: string | null
          buyer_id: string
          created_at?: string
          currency_code?: string
          id?: string
          idempotency_key?: string | null
          marketplace_context: Database['public']['Enums']['marketplace_context']
          shipping_address?: Json | null
          shipping_cents?: number
          status?: Database['public']['Enums']['order_status']
          stripe_checkout_session_id?: string | null
          stripe_payment_intent_id?: string | null
          subtotal_cents: number
          supplier_id: string
          total_cents: number
          updated_at?: string
          vat_cents?: number
        }
        Update: {
          broker_id?: string | null
          buyer_country_id?: string | null
          buyer_id?: string
          created_at?: string
          currency_code?: string
          id?: string
          idempotency_key?: string | null
          marketplace_context?: Database['public']['Enums']['marketplace_context']
          shipping_address?: Json | null
          shipping_cents?: number
          status?: Database['public']['Enums']['order_status']
          stripe_checkout_session_id?: string | null
          stripe_payment_intent_id?: string | null
          subtotal_cents?: number
          supplier_id?: string
          total_cents?: number
          updated_at?: string
          vat_cents?: number
        }
      }
      payouts: {
        Row: {
          amount_cents: number
          completed_at: string | null
          created_at: string
          currency_code: string
          id: string
          recipient_id: string
          recipient_type: string
          status: Database['public']['Enums']['payout_status']
          stripe_transfer_id: string | null
        }
        Insert: {
          amount_cents: number
          completed_at?: string | null
          created_at?: string
          currency_code?: string
          id?: string
          recipient_id: string
          recipient_type: string
          status?: Database['public']['Enums']['payout_status']
          stripe_transfer_id?: string | null
        }
        Update: {
          amount_cents?: number
          completed_at?: string | null
          created_at?: string
          currency_code?: string
          id?: string
          recipient_id?: string
          recipient_type?: string
          status?: Database['public']['Enums']['payout_status']
          stripe_transfer_id?: string | null
        }
      }
      product_images: {
        Row: {
          id: string
          product_id: string
          sort_order: number
          url: string
        }
        Insert: {
          id?: string
          product_id: string
          sort_order?: number
          url: string
        }
        Update: {
          id?: string
          product_id?: string
          sort_order?: number
          url?: string
        }
      }
      products: {
        Row: {
          category_id: string
          city_id: string | null
          created_at: string
          currency_code: string
          description: string | null
          id: string
          is_published: boolean
          marketplace_context: Database['public']['Enums']['marketplace_context']
          min_order_qty: number
          name: string
          price_cents: number
          sku: string | null
          slug: string
          stock_qty: number
          supplier_id: string
          updated_at: string
          vat_rate: number | null
          weight_grams: number | null
        }
        Insert: {
          category_id: string
          city_id?: string | null
          created_at?: string
          currency_code?: string
          description?: string | null
          id?: string
          is_published?: boolean
          marketplace_context: Database['public']['Enums']['marketplace_context']
          min_order_qty?: number
          name: string
          price_cents: number
          sku?: string | null
          slug: string
          stock_qty?: number
          supplier_id: string
          updated_at?: string
          vat_rate?: number | null
          weight_grams?: number | null
        }
        Update: {
          category_id?: string
          city_id?: string | null
          created_at?: string
          currency_code?: string
          description?: string | null
          id?: string
          is_published?: boolean
          marketplace_context?: Database['public']['Enums']['marketplace_context']
          min_order_qty?: number
          name?: string
          price_cents?: number
          sku?: string | null
          slug?: string
          stock_qty?: number
          supplier_id?: string
          updated_at?: string
          vat_rate?: number | null
          weight_grams?: number | null
        }
      }
      profiles: {
        Row: {
          city_id: string | null
          country_id: string | null
          created_at: string
          full_name: string | null
          id: string
          phone: string | null
          preferred_language: string | null
          role: Database['public']['Enums']['user_role']
          updated_at: string
        }
        Insert: {
          city_id?: string | null
          country_id?: string | null
          created_at?: string
          full_name?: string | null
          id: string
          phone?: string | null
          preferred_language?: string | null
          role?: Database['public']['Enums']['user_role']
          updated_at?: string
        }
        Update: {
          city_id?: string | null
          country_id?: string | null
          created_at?: string
          full_name?: string | null
          id?: string
          phone?: string | null
          preferred_language?: string | null
          role?: Database['public']['Enums']['user_role']
          updated_at?: string
        }
      }
      supplier_documents: {
        Row: {
          doc_type: string
          file_url: string
          id: string
          supplier_id: string
          uploaded_at: string
        }
        Insert: {
          doc_type: string
          file_url: string
          id?: string
          supplier_id: string
          uploaded_at?: string
        }
        Update: {
          doc_type?: string
          file_url?: string
          id?: string
          supplier_id?: string
          uploaded_at?: string
        }
      }
      supplier_state_audit: {
        Row: {
          actor_id: string | null
          created_at: string
          from_status: Database['public']['Enums']['supplier_status'] | null
          id: string
          reason: string | null
          supplier_id: string
          to_status: Database['public']['Enums']['supplier_status']
        }
        Insert: {
          actor_id?: string | null
          created_at?: string
          from_status?: Database['public']['Enums']['supplier_status'] | null
          id?: string
          reason?: string | null
          supplier_id: string
          to_status: Database['public']['Enums']['supplier_status']
        }
        Update: {
          actor_id?: string | null
          created_at?: string
          from_status?: Database['public']['Enums']['supplier_status'] | null
          id?: string
          reason?: string | null
          supplier_id?: string
          to_status?: Database['public']['Enums']['supplier_status']
        }
      }
      suppliers: {
        Row: {
          address_line1: string | null
          address_line2: string | null
          admin_notes: string | null
          city_id: string | null
          country_id: string
          created_at: string
          description: string | null
          id: string
          legal_name: string
          logo_url: string | null
          marketplace_context: Database['public']['Enums']['marketplace_context']
          owner_id: string
          postal_code: string | null
          reliability_tier: Database['public']['Enums']['reliability_tier']
          status: Database['public']['Enums']['supplier_status']
          tax_id: string
          trade_name: string | null
          updated_at: string
          vat_number: string | null
          verified_at: string | null
        }
        Insert: {
          address_line1?: string | null
          address_line2?: string | null
          admin_notes?: string | null
          city_id?: string | null
          country_id: string
          created_at?: string
          description?: string | null
          id?: string
          legal_name: string
          logo_url?: string | null
          marketplace_context?: Database['public']['Enums']['marketplace_context']
          owner_id: string
          postal_code?: string | null
          reliability_tier?: Database['public']['Enums']['reliability_tier']
          status?: Database['public']['Enums']['supplier_status']
          tax_id: string
          trade_name?: string | null
          updated_at?: string
          vat_number?: string | null
          verified_at?: string | null
        }
        Update: {
          address_line1?: string | null
          address_line2?: string | null
          admin_notes?: string | null
          city_id?: string | null
          country_id?: string
          created_at?: string
          description?: string | null
          id?: string
          legal_name?: string
          logo_url?: string | null
          marketplace_context?: Database['public']['Enums']['marketplace_context']
          owner_id?: string
          postal_code?: string | null
          reliability_tier?: Database['public']['Enums']['reliability_tier']
          status?: Database['public']['Enums']['supplier_status']
          tax_id?: string
          trade_name?: string | null
          updated_at?: string
          vat_number?: string | null
          verified_at?: string | null
        }
      }
      transaction_ledger: {
        Row: {
          broker_net_cents: number
          created_at: string
          currency_code: string
          gross_cents: number
          id: string
          order_id: string
          processor_fee_cents: number
          settled_at: string | null
          supplier_net_cents: number
          ttai_commission_cents: number
          ttai_fixed_cents: number
          vat_collected_cents: number
        }
        Insert: {
          broker_net_cents?: number
          created_at?: string
          currency_code?: string
          gross_cents: number
          id?: string
          order_id: string
          processor_fee_cents?: number
          settled_at?: string | null
          supplier_net_cents: number
          ttai_commission_cents?: number
          ttai_fixed_cents?: number
          vat_collected_cents?: number
        }
        Update: {
          broker_net_cents?: number
          created_at?: string
          currency_code?: string
          gross_cents?: number
          id?: string
          order_id?: string
          processor_fee_cents?: number
          settled_at?: string | null
          supplier_net_cents?: number
          ttai_commission_cents?: number
          ttai_fixed_cents?: number
          vat_collected_cents?: number
        }
      }
    }
    Views: Record<string, never>
    Functions: {
      current_user_role: {
        Args: Record<PropertyKey, never>
        Returns: string
      }
      generate_invoice_number: {
        Args: Record<PropertyKey, never>
        Returns: string
      }
      broker_assigned_to_supplier: {
        Args: { p_broker_id: string; p_supplier_id: string }
        Returns: boolean
      }
    }
    Enums: {
      invoice_status: 'draft' | 'pending_conditions' | 'issued' | 'paid' | 'void'
      marketplace_context: 'wholesale' | 'retail' | 'both'
      order_status: 'pending' | 'paid' | 'fulfilled' | 'delivered' | 'cancelled' | 'refunded' | 'disputed'
      payout_status: 'pending' | 'processing' | 'completed' | 'failed'
      reliability_tier: 'UNVERIFIED' | 'BRONZE' | 'SILVER' | 'GOLD'
      supplier_status: 'PENDING' | 'UNDER_REVIEW' | 'ACTIVE' | 'SUSPENDED'
      user_role: 'buyer' | 'business_client' | 'supplier' | 'broker' | 'admin'
    }
  }
}
